/**
 * MatchaMap 표준 에러 코드. 콜러블 응답 `details.code`에 첨부.
 * iOS 클라이언트(`Domain/Error.swift`)와 1:1 정합. 추가/변경 시 양측 동시 PR.
 */
export const ErrorCodes = {
  // Auth / App Check
  APP_CHECK_FAILED: 'APP_CHECK_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',

  // Validation
  INVALID_ARGUMENT: 'INVALID_ARGUMENT',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_EXHAUSTED: 'RESOURCE_EXHAUSTED',

  // Domain — 광고/도감
  REWARDED_AD_INVALID_SIGNATURE: 'REWARDED_AD_INVALID_SIGNATURE',
  REWARDED_AD_REPLAY: 'REWARDED_AD_REPLAY',
  REWARDED_AD_QUOTA_EXCEEDED: 'REWARDED_AD_QUOTA_EXCEEDED',
  COLLECTION_SLOT_ALREADY_UNLOCKED: 'COLLECTION_SLOT_ALREADY_UNLOCKED',

  // Domain — 모더레이션
  MODERATION_REJECTED: 'MODERATION_REJECTED',
  MODERATION_PENDING: 'MODERATION_PENDING',

  // Internal
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
